### ISSUE TITLE
Blkw 1

### ISSUE THREAD

**Issue by EmilyClaire** [WChargin/lc3#1]
Numeric literals throw an error when used with blkw.

**Comment by WChargin** [comment]
Try either `.BLKW #1` or `.BLKW x1`?

Page 524 of the book lists only &ldquo;`x`<i>Number</i>&rdquo; and &ldquo;`#`<i>Number</i>&rdquo; as the numeric literal formats. Some other interpreters may choose to accept more implementation-defined formats, like just &ldquo;<i>Number</i>&rdquo;, but they need not.

Feel free to reopen if this doesn't resolve your question.
